# This is a basic workflow to help you get started with Actions

name: tagincrement
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ellerbrock/alpine-bash-curl-ssl
      options: --user root -v /__w/${{ github.workspace }}:/scripts/:rw
    env:
      working-directory: ./
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git Checks-out
      uses: actions/checkout@v1
    - name: tag
      env:
        GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
        REPO_OWNER: Anusha-Kolli
      run: |
        chmod +x scripts/tag.sh
        awk  -v tag='"$current_tag"' '/Unreleased/ {p=1;next}; /'"$current_tag"'/ {p=0} p' CHANGELOG.md 
        ./scripts/tag.sh "$new_tag" "$current_tag"

        