# This is a basic workflow to help you get started with Actions

name: createRelease
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: alpine:3.10
      options: --user root -v /__w/${{ github.workspace }}:/scripts/:rw
    env:
      working-directory: ./
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git Checks-out
      uses: actions/checkout@v1
    - name: create a release
      env:
        GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
        REPO_OWNER: Anusha-Kolli
        USER: ${{secrets.USER}}
        PASSWORD: ${{secrets.PASSWORD}}
      run: |
        apk --update add bash curl git docker
        ./scripts/tag.sh

        
