# This is a basic workflow to help you get started with Actions

name: createRelease
on:
  push:
    branches:
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: alpine:3.10
      options: --user root -v /__w/${{ github.workspace }}:/scripts/:rw
    env:
      working-directory: ./
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git Checks-out
      uses: actions/checkout@v1
    - name: create a release
      env:
        GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
        USER: ${{secrets.USER}}
        PASSWORD: ${{secrets.PASSWORD}}
        REGISTRY: ${{secrets.REGISTRY}}
        REPO_OWNER: Anusha-Kolli
      run: |
        echo EXTRACT_GITHUB_REF=${GITHUB_REF##*/}
        apk --update add bash curl git docker openssl
        ./scripts/tag.sh
    - name: repository dispatch
      run: |
        apk --update add bash curl git jq
        curl -s -X POST $GITHUB_API_URL/repos/Anusha-Kolli/test-dispatch/actions/workflows/$GITHUB_RUNNNER_ID/dispatches -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" \
        -d @- << EOF
         {
           "ref":"develop",
            "event_type": "build_application"
          }    
        EOF



        
