# This is a basic workflow to help you get started with Actions

name: createRelease
on:
  push:
    branches:
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: debian:stretch-slim
      options: --user root -v /__w/${{ github.workspace }}:/scripts/:rw
    env:
      working-directory: ./
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git Checks-out
      uses: actions/checkout@v1
    - name: create a release
      env:
        GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
        USER: ${{secrets.USER}}
        PASSWORD: ${{secrets.PASSWORD}}
        REGISTRY: ${{secrets.REGISTRY}}
        REPO_OWNER: Anusha-Kolli
      run: |
        echo EXTRACT_GITHUB_REF=${GITHUB_REF##*/}
        apt update && apt install -y curl git openssl
        apt update && apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common
        curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
        apt install docker-ce
        ./scripts/tag.sh
    - name: repository dispatch
      env:
        GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
      run: |
        apt update && apt install -y bash curl git jq
        curl -s -X POST $GITHUB_API_URL/repos/Anusha-Kolli/test-dispatch/dispatches \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $GITHUB_TOKEN" \
        -d @- << EOF
         {
           "event_type": "build_application",
           "client_payload": { "repository": "$GITHUB_REPOSITORY" }
        }    
        EOF



        
